### ISSUE TITLE
typo in generate_description_compare() function? 

### ISSUE THREAD

**Issue by ltong1130ztr** [Zhiyuan-R/ChatGPT-Powered-Hierarchical-Comparisons-for-Image-Classification#2]
https://github.com/Zhiyuan-R/ChatGPT-Powered-Hierarchical-Comparisons-for-Image-Classification/blob/f2eb809da4479030d6009b8e6c1a64b8d5e1fa5b/generate_tree.py#L263

`prompt = generate_prompt_compare(categories_group, string)`

Should be:

`prompt = generate_prompt_compare(x, string)`

as `categories_group ` is a list of categories, not a string

**Comment by Zhiyuan-R** [comment]
I think you are absolutely right! Sorry for making this typo when cleaning my code base. Please feel free to discuss here if you have issues to get reasonable results.
